### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by dbaynard** [zwhitchcox/crouton-clipboard#1]
Hello,

I’m getting the above message every time I copy content. Running with `--trace-warnings` gives:

```
DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at maybeCallback (fs.js:98:42)
    at Object.fs.writeFile (fs.js:1284:14)
    at WebSocket.ws.on.msg (~/.crouton-clipboard/server.js:12:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver.ontext (~/.crouton-clipboard/node_modules/ws/lib/WebSocket.js:841:10)
    at ~/.crouton-clipboard/node_modules/ws/lib/Receiver.js:536:18
    at ~/.crouton-clipboard/node_modules/ws/lib/Receiver.js:368:7
    at ~/.crouton-clipboard/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:383:3)
```

(I run with `2>/dev/null` to prevent the error message from appearing as a temporary measure).

**Comment by zwhitchcox** [comment]
Ok, thanks...the new version should fix that...Idk, I might need to add that `2>/dev/null` in order to keep it from happening again though

**Comment by zwhitchcox** [comment]
Yeah, I just added your hack to the main launch script https://github.com/zwhitchcox/crouton-clipboard/blob/master/install.sh

**Comment by dbaynard** [comment]
Well that'd just hide it next time…

I made a few more edits (mostly to documentation) and I'll submit them as PRs.
